spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: qwerty
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml